### ISSUE TITLE
oauth2client Depreciated 

### ISSUE THREAD

**Issue by mapleleafnj** [andywalden/gsuite2mfe#3]
Any ideas for how to convert oauth2client to google-auth-client ? 

from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

**Comment by andywalden** [comment]
Fixed in 1.0.0. Thanks.

**Comment by mapleleafnj** [comment]
Thank you very much ...
Great job ...
