### ISSUE TITLE
Gsuite Permissions .... 

### ISSUE THREAD

**Issue by mapleleafnj** [andywalden/gsuite2mfe#4]
Outside of Super Admin, is there a minimum security level that can be used to access what is needed ?

Thanks

**Comment by andywalden** [comment]
Sorry, Google's rules: https://developers.google.com/admin-sdk/reports/v1/guides/prerequisites

"As a prerequisite to using the API, the documentation assumes you have completed these setup steps....Get a G Suite account and *create an administrator*. You can create user accounts and delegate administrator privileges from the G Suite Admin console or using the Directory API. "

**Comment by mapleleafnj** [comment]
thank you very much.

Your quick feedback is much appreciated ..
