### ISSUE TITLE
Missing quickstart.py

### ISSUE THREAD

**Issue by sebdooris** [andywalden/gsuite2mfe#5]
Just installing from fresh and it looks like quickstart.py is now missing from the repo. 

`(gsuite2mfe) [root@XXXX gsuite2mfe]# python quickstart.py --noauth_local_webserver
python: can't open file 'quickstart.py': [Errno 2] No such file or directory
`

**Comment by andywalden** [comment]
Sorry - deprecated steps that should have been left out of the latest readme. I made an edit to remove the old info. Can you give it a try with what's there and let me know? Thanks.

**Comment by andywalden** [comment]
An updated quickstart.py file is maintained here: https://github.com/gsuitedevs/python-samples/blob/master/admin_sdk/reports/quickstart.py
